### PR TITLE
API fixing

### PR DESCRIPTION
**Pull request by joaquinperaza**
Google is asking a 302 redirect sometimes causing loss of parameters and getting an erroneous response with AED->AED 1->1 conversion

### CODE REVIEW

**Comment by amenoni** [comment]
Please pull this asap, my app is down because of this bug 

Thanks

**Comment by joaquinperaza** [comment]
Hi @amenoni, actually you can reference you package.json to:
`"google-currency": "https://github.com/joaquinperaza/google-currency/tarball/master"`
and install with `npm install joaquinperaza/google-currency`
Regards.
Joaquin.

**Comment by muhilham** [comment]
hi @joaquinperaza . thx for this :). do you have any npmjs account ? If you do, i hope you are okay to be the collaborator on google-currency npm package

**Comment by joaquinperaza** [comment]
Hi @muhilham, thx you for merging, yes I agree with that, my username is the same as GitHub.

**Pull request merged**
